# Generated by Django 4.2.6 on 2023-10-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='loginmodel',
            name='created',
        ),
        migrations.AddField(
            model_name='loginmodel',
            name='password',
            field=models.CharField(default='default_password_value', max_length=100),
        ),
    ]
