# Generated by Django 4.2.6 on 2023-10-30 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_rename_password_loginmodel_password1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginmodel',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='loginmodel',
            name='password2',
        ),
    ]
